In [1]:
import numpy as np

## Est-ce qu'un ANN peur apprendre à dire si un eleve a son bac ou pas

### Création d'un dataset d'élèves, de notes et leur résultat au bac

In [2]:
# Je veux créer une matrice avec 4 lignes(dont chacune represente une matière) 
#et 200 colonnes pour les exemples d'éleves
n_matieres   = 4
n_eleves     = 200
note_maximal = 20
X = np.random.randint(note_maximal + 1, # pour retourner des nombres entre 0 et 20 (inclus)
                      size=(n_matieres,
                            n_eleves))

X.shape

(4, 200)

In [4]:
len(X[0, :])

200

In [5]:
# A partir de notre dataset X, je crée mon label Y qui renvoie aux résultats des élèves 
#c'est à dire s'ils passent le bac ou pas
coeffs = np.array([2, 4, 2, 6])
coeffs.shape



(4,)

In [6]:
coeffs = coeffs.reshape(4, 1)

In [7]:
coeffs

array([[2],
       [4],
       [2],
       [6]])

In [8]:
score_bac = np.dot(X.T, coeffs)


In [9]:
score_bac.shape

(200, 1)

In [10]:
moyenne = score_bac/np.sum(coeffs)

In [12]:
moyenne[:10]


array([[14.        ],
       [15.        ],
       [ 5.85714286],
       [ 6.85714286],
       [16.42857143],
       [18.28571429],
       [12.14285714],
       [12.85714286],
       [ 4.71428571],
       [ 7.71428571]])

In [15]:
Y = (moyenne>=10)*1

In [16]:
Y

array([[1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
    